"""
Generates a tiny random-weight FalconMamba checkpoint for fast local testing.

Produces an untrained FalconMambaForCausalLM small enough to load and run
in well under a second, so the falcon-mamba architecture support can be
exercised without downloading or holding the real ~7B tiiuae/falcon-mamba-7b
checkpoint in memory. Output text will be gibberish since the weights are
random - this is for testing the plumbing, not model quality. Run once;
re-run to regenerate with different dimensions.
"""

from pathlib import Path

from transformers import AutoTokenizer, FalconMambaConfig, FalconMambaForCausalLM

REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKPOINT_DIR = REPO_ROOT / "checkpoints" / "dummy-falcon-mamba-tiny"
MANIFEST_PATH = REPO_ROOT / "manifests" / "dummy-falcon-mamba-tiny.yaml"
TOKENIZER_ID = "EleutherAI/gpt-neox-20b"
HIDDEN_SIZE = 64
NUM_LAYERS = 4
STATE_SIZE = 8

MANIFEST_TEMPLATE = """\
# Tiny random-weight FalconMamba model for fast local testing (~3M params).
# Generated by scripts/make_dummy_falcon_mamba_manifest.py - output is
# gibberish since the weights are untrained, this is for exercising the
# pipeline quickly, not model quality. `checkpoint` is relative to the repo
# root, so the orchestrator must be run from there (as `make
# run-orchestrator` already does).
name: dummy-falcon-mamba-tiny
arch: falcon-mamba
checkpoint: checkpoints/dummy-falcon-mamba-tiny
layers: {layers}
hidden_dim: {hidden_dim}
state_dim: {state_dim}
input_type: text
tokenizer: {tokenizer}
"""


def main() -> None:
    """
    Build and save the dummy checkpoint, and write its manifest.
    """
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_ID)
    config = FalconMambaConfig(
        vocab_size=len(tokenizer),
        hidden_size=HIDDEN_SIZE,
        num_hidden_layers=NUM_LAYERS,
        state_size=STATE_SIZE,
    )
    model = FalconMambaForCausalLM(config)
    num_params = sum(p.numel() for p in model.parameters())

    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(CHECKPOINT_DIR)

    MANIFEST_PATH.write_text(
        MANIFEST_TEMPLATE.format(
            layers=NUM_LAYERS,
            hidden_dim=HIDDEN_SIZE,
            state_dim=STATE_SIZE,
            tokenizer=TOKENIZER_ID,
        )
    )

    print(f"Saved {num_params:,} param dummy model to {CHECKPOINT_DIR}")
    print(f"Wrote manifest to {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
